### PR TITLE
Add support for UPN and URI SAN types

### PR DESCRIPTION
**Pull request by wgoulet**
This PR updates vcert-python to support additional SAN types, userPrincipalName and URL. The UPN extension was added per MS OID specifications. A fix to the tests was also made to ensure that custom extensions are added; the enroll method in test_e2e.py was not properly evaluating the connection type and was skipping the code that added custom extensions to CSR. Also made a minor update to the README to help developers that are actively updating vcert-python itself. Note: this was developed and tested in Python 3 only.

### CODE REVIEW

**Comment by angelmoo** [comment]
@wgoulet did you run all the vcert-python's test suit and passed?, since I see that you only test it on python 3, at this moment we need to ensure that it works with python 2 as well.

**Comment by wgoulet** [comment]
I ran all the TPP tests in test_e2e.py; the only failing tests I noticed
were the test_tpp_enroll_with_custom_csr tests because the test csr is not
included in the repo. I did not attempt to add support for python 2.

**Comment by wgoulet** [comment]
@angelmoo @tr1ck3r I created a new branch that adds support for UPN and URIs for python 2 as well. After further investigation, I do not think we will be able to have a single module that works for python 2 & 3 simultaneously with my changes. I confirmed this by setting up a python 3 virtual environment and running the tests against my python 2 branch. As I suspected, due to differences in how python 2 & 3 handle strings vs byte objects, I cannot use the x509 crypto library as is to add the UPN extension. I can submit another PR for my python 2 branch if you'd like to make it easier to review.

**Comment by tr1ck3r** [comment]
https://github.com/Venafi/vcert-python/compare/master...wgoulet:add-upn-san-support-py2

**Comment by wgoulet** [comment]
@angelmoo @tr1ck3r Latest commits to my branch add support for python2. Tested locally with python2 and 3 and verified the TPP tests pass. Can you run my branch against your test automation (I cannot complete the enroll_with_custom_csr tests without a copy of the csr being used, might be good to include that file in the repo)?

**Comment by tr1ck3r** [comment]
Looks like you got it fixed 😃 I just ran our test automation against your `add-upn-san-support` branch and the job completed successfully.  @angelmoo @rvelaVenafi please proceed with the code review.

**Review by rvelaVenafi — APPROVED** [review]
Looks very solid, addresses python 2 and 3.

**Review by angelmoo — APPROVED** [review]
code looks good.

**Comment by tr1ck3r** [comment]
Thank you for your contribution @wgoulet 😃

**Comment by wgoulet** [comment]
Happy to help and hope it’s useful to the community!

**Pull request merged**
